FROM ubuntu:18.04


RUN apt-get update && apt-get install -y wget && apt-get install -y inotify-tools && apt-get install -y git
RUN wget -c https://repo.continuum.io/miniconda/Miniconda2-4.5.4-Linux-x86_64.sh && bash Miniconda2-4.5.4-Linux-x86_64.sh -b -p && rm Miniconda2-4.5.4-Linux-x86_64.sh

RUN ~/miniconda2/bin/conda install --yes mysql-python

RUN mkdir /app && cd /app && ~/miniconda2/bin/conda create -n image_handler numpy h5py==2.8.0 pillow==6 mysql-python && . ~/miniconda2/bin/activate image_handler && git clone https://github.com/tim-inzitari/deepzoom.py.git && mv deepzoom.py dzp && cd dzp && python setup.py install

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Run app.py when the container launches
CMD ["./runner.sh"]
